version: '3.9'
services:
  leader:
    build: .
    command: ["-port", "6379", "-dir", "/data", "-dbfilename", "dump.rdb", "-appendonly", "true", "-appendfilename", "appendonly.aof"]
    volumes:
      - voltcache-data:/data
    ports:
      - "6379:6379"
  replica:
    build: .
    command: ["-port", "6380", "-replicaof", "leader 6379", "-dir", "/data", "-dbfilename", "dump.rdb", "-appendonly", "true", "-appendfilename", "appendonly.aof"]
    depends_on:
      - leader
    volumes:
      - voltcache-data:/data
    ports:
      - "6380:6380"
volumes:
  voltcache-data:
